//! Generated Matter TLV encoders and decoders for Administrator Commissioning Cluster
//! Cluster ID: 0x003C
//!
//! This file is automatically generated from AdminCommissioningCluster.xml

use crate::tlv;
use anyhow;
use serde_json;


// Enum definitions

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[repr(u8)]
pub enum CommissioningWindowStatus {
    /// Commissioning window not open
    Windownotopen = 0,
    /// An Enhanced Commissioning Method window is open
    Enhancedwindowopen = 1,
    /// A Basic Commissioning Method window is open
    Basicwindowopen = 2,
}

impl CommissioningWindowStatus {
    /// Convert from u8 value
    pub fn from_u8(value: u8) -> Option<Self> {
        match value {
            0 => Some(CommissioningWindowStatus::Windownotopen),
            1 => Some(CommissioningWindowStatus::Enhancedwindowopen),
            2 => Some(CommissioningWindowStatus::Basicwindowopen),
            _ => None,
        }
    }

    /// Convert to u8 value
    pub fn to_u8(self) -> u8 {
        self as u8
    }
}

impl From<CommissioningWindowStatus> for u8 {
    fn from(val: CommissioningWindowStatus) -> Self {
        val as u8
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[repr(u8)]
pub enum StatusCode {
    /// Could not be completed because another commissioning is in progress
    Busy = 2,
    /// Provided PAKE parameters were incorrectly formatted or otherwise invalid
    Pakeparametererror = 3,
    /// No commissioning window was currently open
    Windownotopen = 4,
}

impl StatusCode {
    /// Convert from u8 value
    pub fn from_u8(value: u8) -> Option<Self> {
        match value {
            2 => Some(StatusCode::Busy),
            3 => Some(StatusCode::Pakeparametererror),
            4 => Some(StatusCode::Windownotopen),
            _ => None,
        }
    }

    /// Convert to u8 value
    pub fn to_u8(self) -> u8 {
        self as u8
    }
}

impl From<StatusCode> for u8 {
    fn from(val: StatusCode) -> Self {
        val as u8
    }
}

// Command encoders

/// Encode OpenCommissioningWindow command (0x00)
pub fn encode_open_commissioning_window(commissioning_timeout: u16, pake_passcode_verifier: Vec<u8>, discriminator: u16, iterations: u32, salt: Vec<u8>) -> anyhow::Result<Vec<u8>> {
    let tlv = tlv::TlvItemEnc {
        tag: 0,
        value: tlv::TlvItemValueEnc::StructInvisible(vec![
        (0, tlv::TlvItemValueEnc::UInt16(commissioning_timeout)).into(),
        (1, tlv::TlvItemValueEnc::OctetString(pake_passcode_verifier)).into(),
        (2, tlv::TlvItemValueEnc::UInt16(discriminator)).into(),
        (3, tlv::TlvItemValueEnc::UInt32(iterations)).into(),
        (4, tlv::TlvItemValueEnc::OctetString(salt)).into(),
        ]),
    };
    Ok(tlv.encode()?)
}

/// Encode OpenBasicCommissioningWindow command (0x01)
pub fn encode_open_basic_commissioning_window(commissioning_timeout: u16) -> anyhow::Result<Vec<u8>> {
    let tlv = tlv::TlvItemEnc {
        tag: 0,
        value: tlv::TlvItemValueEnc::StructInvisible(vec![
        (0, tlv::TlvItemValueEnc::UInt16(commissioning_timeout)).into(),
        ]),
    };
    Ok(tlv.encode()?)
}

// Attribute decoders

/// Decode WindowStatus attribute (0x0000)
pub fn decode_window_status(inp: &tlv::TlvItemValue) -> anyhow::Result<CommissioningWindowStatus> {
    if let tlv::TlvItemValue::Int(v) = inp {
        CommissioningWindowStatus::from_u8(*v as u8).ok_or_else(|| anyhow::anyhow!("Invalid enum value"))
    } else {
        Err(anyhow::anyhow!("Expected Integer"))
    }
}

/// Decode AdminFabricIndex attribute (0x0001)
pub fn decode_admin_fabric_index(inp: &tlv::TlvItemValue) -> anyhow::Result<Option<u8>> {
    if let tlv::TlvItemValue::Int(v) = inp {
        Ok(Some(*v as u8))
    } else {
        Ok(None)
    }
}

/// Decode AdminVendorId attribute (0x0002)
pub fn decode_admin_vendor_id(inp: &tlv::TlvItemValue) -> anyhow::Result<Option<u16>> {
    if let tlv::TlvItemValue::Int(v) = inp {
        Ok(Some(*v as u16))
    } else {
        Ok(None)
    }
}


// JSON dispatcher function

/// Decode attribute value and return as JSON string
/// 
/// # Parameters
/// * `cluster_id` - The cluster identifier
/// * `attribute_id` - The attribute identifier
/// * `tlv_value` - The TLV value to decode
/// 
/// # Returns
/// JSON string representation of the decoded value or error
pub fn decode_attribute_json(cluster_id: u32, attribute_id: u32, tlv_value: &crate::tlv::TlvItemValue) -> String {
    // Verify this is the correct cluster
    if cluster_id != 0x003C {
        return format!("{{\"error\": \"Invalid cluster ID. Expected 0x003C, got {}\"}}", cluster_id);
    }
    
    match attribute_id {
        0x0000 => {
            match decode_window_status(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0001 => {
            match decode_admin_fabric_index(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0002 => {
            match decode_admin_vendor_id(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        _ => format!("{{\"error\": \"Unknown attribute ID: {}\"}}", attribute_id),
    }
}

/// Get list of all attributes supported by this cluster
/// 
/// # Returns
/// Vector of tuples containing (attribute_id, attribute_name)
pub fn get_attribute_list() -> Vec<(u32, &'static str)> {
    vec![
        (0x0000, "WindowStatus"),
        (0x0001, "AdminFabricIndex"),
        (0x0002, "AdminVendorId"),
    ]
}

