//! Matter TLV encoders and decoders for Low Power Cluster
//! Cluster ID: 0x0508
//!
//! This file is automatically generated from LowPower.xml

#![allow(clippy::too_many_arguments)]



// Command encoders

// Typed facade (invokes + reads)

/// Invoke `Sleep` command on cluster `Low Power`.
pub async fn sleep(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<()> {
    conn.invoke_request(endpoint, crate::clusters::defs::CLUSTER_ID_LOW_POWER, crate::clusters::defs::CLUSTER_LOW_POWER_CMD_ID_SLEEP, &[]).await?;
    Ok(())
}

