//! Matter TLV encoders and decoders for Network Commissioning Cluster
//! Cluster ID: 0x0031
//!
//! This file is automatically generated from NetworkCommissioningCluster.xml

use crate::tlv;
use anyhow;
use serde_json;


// Import serialization helpers for octet strings
use crate::clusters::helpers::{serialize_opt_bytes_as_hex};

// Enum definitions

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[repr(u8)]
pub enum NetworkCommissioningStatus {
    /// OK, no error
    Success = 0,
    /// Value Outside Range
    Outofrange = 1,
    /// A collection would exceed its size limit
    Boundsexceeded = 2,
    /// The NetworkID is not among the collection of added networks
    Networkidnotfound = 3,
    /// The NetworkID is already among the collection of added networks
    Duplicatenetworkid = 4,
    /// Cannot find AP: SSID Not found
    Networknotfound = 5,
    /// Cannot find AP: Mismatch on band/channels/regulatory domain / 2.4GHz vs 5GHz
    Regulatoryerror = 6,
    /// Cannot associate due to authentication failure
    Authfailure = 7,
    /// Cannot associate due to unsupported security mode
    Unsupportedsecurity = 8,
    /// Other association failure
    Otherconnectionfailure = 9,
    /// Failure to generate an IPv6 address
    Ipv6failed = 10,
    /// Failure to bind Wi-Fi +<->+ IP interfaces
    Ipbindfailed = 11,
    /// Unknown error
    Unknownerror = 12,
}

impl NetworkCommissioningStatus {
    /// Convert from u8 value
    pub fn from_u8(value: u8) -> Option<Self> {
        match value {
            0 => Some(NetworkCommissioningStatus::Success),
            1 => Some(NetworkCommissioningStatus::Outofrange),
            2 => Some(NetworkCommissioningStatus::Boundsexceeded),
            3 => Some(NetworkCommissioningStatus::Networkidnotfound),
            4 => Some(NetworkCommissioningStatus::Duplicatenetworkid),
            5 => Some(NetworkCommissioningStatus::Networknotfound),
            6 => Some(NetworkCommissioningStatus::Regulatoryerror),
            7 => Some(NetworkCommissioningStatus::Authfailure),
            8 => Some(NetworkCommissioningStatus::Unsupportedsecurity),
            9 => Some(NetworkCommissioningStatus::Otherconnectionfailure),
            10 => Some(NetworkCommissioningStatus::Ipv6failed),
            11 => Some(NetworkCommissioningStatus::Ipbindfailed),
            12 => Some(NetworkCommissioningStatus::Unknownerror),
            _ => None,
        }
    }

    /// Convert to u8 value
    pub fn to_u8(self) -> u8 {
        self as u8
    }
}

impl From<NetworkCommissioningStatus> for u8 {
    fn from(val: NetworkCommissioningStatus) -> Self {
        val as u8
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[repr(u8)]
pub enum WiFiBand {
    /// 2.4GHz - 2.401GHz to 2.495GHz (802.11b/g/n/ax)
    _2g4 = 0,
    /// 3.65GHz - 3.655GHz to 3.695GHz (802.11y)
    _3g65 = 1,
    /// 5GHz - 5.150GHz to 5.895GHz (802.11a/n/ac/ax)
    _5g = 2,
    /// 6GHz - 5.925GHz to 7.125GHz (802.11ax / Wi-Fi 6E)
    _6g = 3,
    /// 60GHz - 57.24GHz to 70.20GHz (802.11ad/ay)
    _60g = 4,
    /// Sub-1GHz - 755MHz to 931MHz (802.11ah)
    _1g = 5,
}

impl WiFiBand {
    /// Convert from u8 value
    pub fn from_u8(value: u8) -> Option<Self> {
        match value {
            0 => Some(WiFiBand::_2g4),
            1 => Some(WiFiBand::_3g65),
            2 => Some(WiFiBand::_5g),
            3 => Some(WiFiBand::_6g),
            4 => Some(WiFiBand::_60g),
            5 => Some(WiFiBand::_1g),
            _ => None,
        }
    }

    /// Convert to u8 value
    pub fn to_u8(self) -> u8 {
        self as u8
    }
}

impl From<WiFiBand> for u8 {
    fn from(val: WiFiBand) -> Self {
        val as u8
    }
}

// Bitmap definitions

/// ThreadCapabilities bitmap type
pub type ThreadCapabilities = u8;

/// Constants for ThreadCapabilities
pub mod threadcapabilities {
    /// Thread Border Router functionality is present
    pub const IS_BORDER_ROUTER_CAPABLE: u8 = 0x01;
    /// Router mode is supported (interface could be in router or REED mode)
    pub const IS_ROUTER_CAPABLE: u8 = 0x02;
    /// Sleepy end-device mode is supported
    pub const IS_SLEEPY_END_DEVICE_CAPABLE: u8 = 0x04;
    /// Device is a full Thread device (opposite of Minimal Thread Device)
    pub const IS_FULL_THREAD_DEVICE: u8 = 0x08;
    /// Synchronized sleepy end-device mode is supported
    pub const IS_SYNCHRONIZED_SLEEPY_END_DEVICE_CAPABLE: u8 = 0x10;
}

/// WiFiSecurity bitmap type
pub type WiFiSecurity = u8;

/// Constants for WiFiSecurity
pub mod wifisecurity {
    /// Supports unencrypted Wi-Fi
    pub const UNENCRYPTED: u8 = 0x01;
    /// Supports Wi-Fi using WEP security
    pub const WEP: u8 = 0x02;
    /// Supports Wi-Fi using WPA-Personal security
    pub const WPA_PERSONAL: u8 = 0x04;
    /// Supports Wi-Fi using WPA2-Personal security
    pub const WPA2_PERSONAL: u8 = 0x08;
    /// Supports Wi-Fi using WPA3-Personal security
    pub const WPA3_PERSONAL: u8 = 0x10;
}

// Struct definitions

#[derive(Debug, serde::Serialize)]
pub struct NetworkInfo {
    #[serde(serialize_with = "serialize_opt_bytes_as_hex")]
    pub network_id: Option<Vec<u8>>,
    pub connected: Option<bool>,
}

#[derive(Debug, serde::Serialize)]
pub struct ThreadInterfaceScanResult {
    pub pan_id: Option<u16>,
    pub extended_pan_id: Option<u64>,
    pub network_name: Option<String>,
    pub channel: Option<u16>,
    pub version: Option<u8>,
    pub extended_address: Option<u8>,
    pub rssi: Option<i8>,
    pub lqi: Option<u8>,
}

#[derive(Debug, serde::Serialize)]
pub struct WiFiInterfaceScanResult {
    pub security: Option<WiFiSecurity>,
    #[serde(serialize_with = "serialize_opt_bytes_as_hex")]
    pub ssid: Option<Vec<u8>>,
    #[serde(serialize_with = "serialize_opt_bytes_as_hex")]
    pub bssid: Option<Vec<u8>>,
    pub channel: Option<u16>,
    pub wifi_band: Option<WiFiBand>,
    pub rssi: Option<i8>,
}

// Command encoders

/// Encode ScanNetworks command (0x00)
pub fn encode_scan_networks(ssid: Option<Vec<u8>>, breadcrumb: u64) -> anyhow::Result<Vec<u8>> {
    let tlv = tlv::TlvItemEnc {
        tag: 0,
        value: tlv::TlvItemValueEnc::StructInvisible(vec![
        (0, tlv::TlvItemValueEnc::OctetString(ssid.unwrap_or_default())).into(),
        (1, tlv::TlvItemValueEnc::UInt64(breadcrumb)).into(),
        ]),
    };
    Ok(tlv.encode()?)
}

/// Encode AddOrUpdateWiFiNetwork command (0x02)
pub fn encode_add_or_update_wifi_network(ssid: Vec<u8>, credentials: Vec<u8>, breadcrumb: u64) -> anyhow::Result<Vec<u8>> {
    let tlv = tlv::TlvItemEnc {
        tag: 0,
        value: tlv::TlvItemValueEnc::StructInvisible(vec![
        (0, tlv::TlvItemValueEnc::OctetString(ssid)).into(),
        (1, tlv::TlvItemValueEnc::OctetString(credentials)).into(),
        (2, tlv::TlvItemValueEnc::UInt64(breadcrumb)).into(),
        ]),
    };
    Ok(tlv.encode()?)
}

/// Encode AddOrUpdateThreadNetwork command (0x03)
pub fn encode_add_or_update_thread_network(operational_dataset: Vec<u8>, breadcrumb: u64) -> anyhow::Result<Vec<u8>> {
    let tlv = tlv::TlvItemEnc {
        tag: 0,
        value: tlv::TlvItemValueEnc::StructInvisible(vec![
        (0, tlv::TlvItemValueEnc::OctetString(operational_dataset)).into(),
        (1, tlv::TlvItemValueEnc::UInt64(breadcrumb)).into(),
        ]),
    };
    Ok(tlv.encode()?)
}

/// Encode RemoveNetwork command (0x04)
pub fn encode_remove_network(network_id: Vec<u8>, breadcrumb: u64) -> anyhow::Result<Vec<u8>> {
    let tlv = tlv::TlvItemEnc {
        tag: 0,
        value: tlv::TlvItemValueEnc::StructInvisible(vec![
        (0, tlv::TlvItemValueEnc::OctetString(network_id)).into(),
        (1, tlv::TlvItemValueEnc::UInt64(breadcrumb)).into(),
        ]),
    };
    Ok(tlv.encode()?)
}

/// Encode ConnectNetwork command (0x06)
pub fn encode_connect_network(network_id: Vec<u8>, breadcrumb: u64) -> anyhow::Result<Vec<u8>> {
    let tlv = tlv::TlvItemEnc {
        tag: 0,
        value: tlv::TlvItemValueEnc::StructInvisible(vec![
        (0, tlv::TlvItemValueEnc::OctetString(network_id)).into(),
        (1, tlv::TlvItemValueEnc::UInt64(breadcrumb)).into(),
        ]),
    };
    Ok(tlv.encode()?)
}

/// Encode ReorderNetwork command (0x08)
pub fn encode_reorder_network(network_id: Vec<u8>, network_index: u8, breadcrumb: u64) -> anyhow::Result<Vec<u8>> {
    let tlv = tlv::TlvItemEnc {
        tag: 0,
        value: tlv::TlvItemValueEnc::StructInvisible(vec![
        (0, tlv::TlvItemValueEnc::OctetString(network_id)).into(),
        (1, tlv::TlvItemValueEnc::UInt8(network_index)).into(),
        (2, tlv::TlvItemValueEnc::UInt64(breadcrumb)).into(),
        ]),
    };
    Ok(tlv.encode()?)
}

// Attribute decoders

/// Decode MaxNetworks attribute (0x0000)
pub fn decode_max_networks(inp: &tlv::TlvItemValue) -> anyhow::Result<u8> {
    if let tlv::TlvItemValue::Int(v) = inp {
        Ok(*v as u8)
    } else {
        Err(anyhow::anyhow!("Expected UInt8"))
    }
}

/// Decode Networks attribute (0x0001)
pub fn decode_networks(inp: &tlv::TlvItemValue) -> anyhow::Result<Vec<NetworkInfo>> {
    let mut res = Vec::new();
    if let tlv::TlvItemValue::List(v) = inp {
        for item in v {
            res.push(NetworkInfo {
                network_id: item.get_octet_string_owned(&[0]),
                connected: item.get_bool(&[1]),
            });
        }
    }
    Ok(res)
}

/// Decode ScanMaxTimeSeconds attribute (0x0002)
pub fn decode_scan_max_time_seconds(inp: &tlv::TlvItemValue) -> anyhow::Result<u8> {
    if let tlv::TlvItemValue::Int(v) = inp {
        Ok(*v as u8)
    } else {
        Err(anyhow::anyhow!("Expected UInt8"))
    }
}

/// Decode ConnectMaxTimeSeconds attribute (0x0003)
pub fn decode_connect_max_time_seconds(inp: &tlv::TlvItemValue) -> anyhow::Result<u8> {
    if let tlv::TlvItemValue::Int(v) = inp {
        Ok(*v as u8)
    } else {
        Err(anyhow::anyhow!("Expected UInt8"))
    }
}

/// Decode InterfaceEnabled attribute (0x0004)
pub fn decode_interface_enabled(inp: &tlv::TlvItemValue) -> anyhow::Result<bool> {
    if let tlv::TlvItemValue::Bool(v) = inp {
        Ok(*v)
    } else {
        Err(anyhow::anyhow!("Expected Bool"))
    }
}

/// Decode LastNetworkingStatus attribute (0x0005)
pub fn decode_last_networking_status(inp: &tlv::TlvItemValue) -> anyhow::Result<Option<NetworkCommissioningStatus>> {
    if let tlv::TlvItemValue::Int(v) = inp {
        Ok(NetworkCommissioningStatus::from_u8(*v as u8))
    } else {
        Ok(None)
    }
}

/// Decode LastNetworkID attribute (0x0006)
pub fn decode_last_network_id(inp: &tlv::TlvItemValue) -> anyhow::Result<Option<Vec<u8>>> {
    if let tlv::TlvItemValue::OctetString(v) = inp {
        Ok(Some(v.clone()))
    } else {
        Ok(None)
    }
}

/// Decode LastConnectErrorValue attribute (0x0007)
pub fn decode_last_connect_error_value(inp: &tlv::TlvItemValue) -> anyhow::Result<Option<i32>> {
    if let tlv::TlvItemValue::Int(v) = inp {
        Ok(Some(*v as i32))
    } else {
        Ok(None)
    }
}

/// Decode SupportedWiFiBands attribute (0x0008)
pub fn decode_supported_wifi_bands(inp: &tlv::TlvItemValue) -> anyhow::Result<Vec<WiFiBand>> {
    let mut res = Vec::new();
    if let tlv::TlvItemValue::List(v) = inp {
        for item in v {
            if let tlv::TlvItemValue::Int(i) = &item.value {
                if let Some(enum_val) = WiFiBand::from_u8(*i as u8) {
                    res.push(enum_val);
                }
            }
        }
    }
    Ok(res)
}

/// Decode SupportedThreadFeatures attribute (0x0009)
pub fn decode_supported_thread_features(inp: &tlv::TlvItemValue) -> anyhow::Result<ThreadCapabilities> {
    if let tlv::TlvItemValue::Int(v) = inp {
        Ok(*v as u8)
    } else {
        Err(anyhow::anyhow!("Expected Integer"))
    }
}

/// Decode ThreadVersion attribute (0x000A)
pub fn decode_thread_version(inp: &tlv::TlvItemValue) -> anyhow::Result<u16> {
    if let tlv::TlvItemValue::Int(v) = inp {
        Ok(*v as u16)
    } else {
        Err(anyhow::anyhow!("Expected UInt16"))
    }
}


// JSON dispatcher function

/// Decode attribute value and return as JSON string
///
/// # Parameters
/// * `cluster_id` - The cluster identifier
/// * `attribute_id` - The attribute identifier
/// * `tlv_value` - The TLV value to decode
///
/// # Returns
/// JSON string representation of the decoded value or error
pub fn decode_attribute_json(cluster_id: u32, attribute_id: u32, tlv_value: &crate::tlv::TlvItemValue) -> String {
    // Verify this is the correct cluster
    if cluster_id != 0x0031 {
        return format!("{{\"error\": \"Invalid cluster ID. Expected 0x0031, got {}\"}}", cluster_id);
    }

    match attribute_id {
        0x0000 => {
            match decode_max_networks(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0001 => {
            match decode_networks(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0002 => {
            match decode_scan_max_time_seconds(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0003 => {
            match decode_connect_max_time_seconds(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0004 => {
            match decode_interface_enabled(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0005 => {
            match decode_last_networking_status(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0006 => {
            match decode_last_network_id(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0007 => {
            match decode_last_connect_error_value(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0008 => {
            match decode_supported_wifi_bands(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0009 => {
            match decode_supported_thread_features(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x000A => {
            match decode_thread_version(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        _ => format!("{{\"error\": \"Unknown attribute ID: {}\"}}", attribute_id),
    }
}

/// Get list of all attributes supported by this cluster
///
/// # Returns
/// Vector of tuples containing (attribute_id, attribute_name)
pub fn get_attribute_list() -> Vec<(u32, &'static str)> {
    vec![
        (0x0000, "MaxNetworks"),
        (0x0001, "Networks"),
        (0x0002, "ScanMaxTimeSeconds"),
        (0x0003, "ConnectMaxTimeSeconds"),
        (0x0004, "InterfaceEnabled"),
        (0x0005, "LastNetworkingStatus"),
        (0x0006, "LastNetworkID"),
        (0x0007, "LastConnectErrorValue"),
        (0x0008, "SupportedWiFiBands"),
        (0x0009, "SupportedThreadFeatures"),
        (0x000A, "ThreadVersion"),
    ]
}

#[derive(Debug, serde::Serialize)]
pub struct ScanNetworksResponse {
    pub networking_status: Option<NetworkCommissioningStatus>,
    pub debug_text: Option<String>,
    pub wifi_scan_results: Option<Vec<WiFiInterfaceScanResult>>,
    pub thread_scan_results: Option<Vec<ThreadInterfaceScanResult>>,
}

#[derive(Debug, serde::Serialize)]
pub struct NetworkConfigResponse {
    pub networking_status: Option<NetworkCommissioningStatus>,
    pub debug_text: Option<String>,
    pub network_index: Option<u8>,
}

#[derive(Debug, serde::Serialize)]
pub struct ConnectNetworkResponse {
    pub networking_status: Option<NetworkCommissioningStatus>,
    pub debug_text: Option<String>,
    pub error_value: Option<i32>,
}

// Command response decoders

/// Decode ScanNetworksResponse command response (01)
pub fn decode_scan_networks_response(inp: &tlv::TlvItemValue) -> anyhow::Result<ScanNetworksResponse> {
    if let tlv::TlvItemValue::List(_fields) = inp {
        let item = tlv::TlvItem { tag: 0, value: inp.clone() };
        Ok(ScanNetworksResponse {
                networking_status: item.get_int(&[0]).and_then(|v| NetworkCommissioningStatus::from_u8(v as u8)),
                debug_text: item.get_string_owned(&[1]),
                wifi_scan_results: {
                    if let Some(tlv::TlvItemValue::List(l)) = item.get(&[2]) {
                        let mut items = Vec::new();
                        for list_item in l {
                            items.push(WiFiInterfaceScanResult {
                security: list_item.get_int(&[0]).map(|v| v as u8),
                ssid: list_item.get_octet_string_owned(&[1]),
                bssid: list_item.get_octet_string_owned(&[2]),
                channel: list_item.get_int(&[3]).map(|v| v as u16),
                wifi_band: list_item.get_int(&[4]).and_then(|v| WiFiBand::from_u8(v as u8)),
                rssi: list_item.get_int(&[5]).map(|v| v as i8),
                            });
                        }
                        Some(items)
                    } else {
                        None
                    }
                },
                thread_scan_results: {
                    if let Some(tlv::TlvItemValue::List(l)) = item.get(&[3]) {
                        let mut items = Vec::new();
                        for list_item in l {
                            items.push(ThreadInterfaceScanResult {
                pan_id: list_item.get_int(&[0]).map(|v| v as u16),
                extended_pan_id: list_item.get_int(&[1]),
                network_name: list_item.get_string_owned(&[2]),
                channel: list_item.get_int(&[3]).map(|v| v as u16),
                version: list_item.get_int(&[4]).map(|v| v as u8),
                extended_address: list_item.get_int(&[5]).map(|v| v as u8),
                rssi: list_item.get_int(&[6]).map(|v| v as i8),
                lqi: list_item.get_int(&[7]).map(|v| v as u8),
                            });
                        }
                        Some(items)
                    } else {
                        None
                    }
                },
        })
    } else {
        Err(anyhow::anyhow!("Expected struct fields"))
    }
}

/// Decode NetworkConfigResponse command response (05)
pub fn decode_network_config_response(inp: &tlv::TlvItemValue) -> anyhow::Result<NetworkConfigResponse> {
    if let tlv::TlvItemValue::List(_fields) = inp {
        let item = tlv::TlvItem { tag: 0, value: inp.clone() };
        Ok(NetworkConfigResponse {
                networking_status: item.get_int(&[0]).and_then(|v| NetworkCommissioningStatus::from_u8(v as u8)),
                debug_text: item.get_string_owned(&[1]),
                network_index: item.get_int(&[2]).map(|v| v as u8),
        })
    } else {
        Err(anyhow::anyhow!("Expected struct fields"))
    }
}

/// Decode ConnectNetworkResponse command response (07)
pub fn decode_connect_network_response(inp: &tlv::TlvItemValue) -> anyhow::Result<ConnectNetworkResponse> {
    if let tlv::TlvItemValue::List(_fields) = inp {
        let item = tlv::TlvItem { tag: 0, value: inp.clone() };
        Ok(ConnectNetworkResponse {
                networking_status: item.get_int(&[0]).and_then(|v| NetworkCommissioningStatus::from_u8(v as u8)),
                debug_text: item.get_string_owned(&[1]),
                error_value: item.get_int(&[2]).map(|v| v as i32),
        })
    } else {
        Err(anyhow::anyhow!("Expected struct fields"))
    }
}

