//! Matter TLV encoders and decoders for Thread Border Router Management Cluster
//! Cluster ID: 0x0452
//!
//! This file is automatically generated from ThreadBorderRouterManagement.xml

#![allow(clippy::too_many_arguments)]

use crate::tlv;
use anyhow;
use serde_json;


// Import serialization helpers for octet strings
use crate::clusters::helpers::{serialize_opt_bytes_as_hex};

// Command encoders

/// Encode SetActiveDatasetRequest command (0x03)
pub fn encode_set_active_dataset_request(active_dataset: Vec<u8>, breadcrumb: Option<u64>) -> anyhow::Result<Vec<u8>> {
    let mut tlv_fields: Vec<tlv::TlvItemEnc> = Vec::new();
    tlv_fields.push((0, tlv::TlvItemValueEnc::OctetString(active_dataset)).into());
    if let Some(x) = breadcrumb { tlv_fields.push((1, tlv::TlvItemValueEnc::UInt64(x)).into()); }
    let tlv = tlv::TlvItemEnc {
        tag: 0,
        value: tlv::TlvItemValueEnc::StructInvisible(tlv_fields),
    };
    Ok(tlv.encode()?)
}

/// Encode SetPendingDatasetRequest command (0x04)
pub fn encode_set_pending_dataset_request(pending_dataset: Vec<u8>) -> anyhow::Result<Vec<u8>> {
    let tlv = tlv::TlvItemEnc {
        tag: 0,
        value: tlv::TlvItemValueEnc::StructInvisible(vec![
        (0, tlv::TlvItemValueEnc::OctetString(pending_dataset)).into(),
        ]),
    };
    Ok(tlv.encode()?)
}

// Attribute decoders

/// Decode BorderRouterName attribute (0x0000)
pub fn decode_border_router_name(inp: &tlv::TlvItemValue) -> anyhow::Result<String> {
    if let tlv::TlvItemValue::String(v) = inp {
        Ok(v.clone())
    } else {
        Err(anyhow::anyhow!("Expected String"))
    }
}

/// Decode BorderAgentID attribute (0x0001)
pub fn decode_border_agent_id(inp: &tlv::TlvItemValue) -> anyhow::Result<Vec<u8>> {
    if let tlv::TlvItemValue::OctetString(v) = inp {
        Ok(v.clone())
    } else {
        Err(anyhow::anyhow!("Expected OctetString"))
    }
}

/// Decode ThreadVersion attribute (0x0002)
pub fn decode_thread_version(inp: &tlv::TlvItemValue) -> anyhow::Result<u16> {
    if let tlv::TlvItemValue::Int(v) = inp {
        Ok(*v as u16)
    } else {
        Err(anyhow::anyhow!("Expected UInt16"))
    }
}

/// Decode InterfaceEnabled attribute (0x0003)
pub fn decode_interface_enabled(inp: &tlv::TlvItemValue) -> anyhow::Result<bool> {
    if let tlv::TlvItemValue::Bool(v) = inp {
        Ok(*v)
    } else {
        Err(anyhow::anyhow!("Expected Bool"))
    }
}

/// Decode ActiveDatasetTimestamp attribute (0x0004)
pub fn decode_active_dataset_timestamp(inp: &tlv::TlvItemValue) -> anyhow::Result<Option<u64>> {
    if let tlv::TlvItemValue::Int(v) = inp {
        Ok(Some(*v))
    } else {
        Ok(None)
    }
}

/// Decode PendingDatasetTimestamp attribute (0x0005)
pub fn decode_pending_dataset_timestamp(inp: &tlv::TlvItemValue) -> anyhow::Result<Option<u64>> {
    if let tlv::TlvItemValue::Int(v) = inp {
        Ok(Some(*v))
    } else {
        Ok(None)
    }
}


// JSON dispatcher function

/// Decode attribute value and return as JSON string
///
/// # Parameters
/// * `cluster_id` - The cluster identifier
/// * `attribute_id` - The attribute identifier
/// * `tlv_value` - The TLV value to decode
///
/// # Returns
/// JSON string representation of the decoded value or error
pub fn decode_attribute_json(cluster_id: u32, attribute_id: u32, tlv_value: &crate::tlv::TlvItemValue) -> String {
    // Verify this is the correct cluster
    if cluster_id != 0x0452 {
        return format!("{{\"error\": \"Invalid cluster ID. Expected 0x0452, got {}\"}}", cluster_id);
    }

    match attribute_id {
        0x0000 => {
            match decode_border_router_name(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0001 => {
            match decode_border_agent_id(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0002 => {
            match decode_thread_version(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0003 => {
            match decode_interface_enabled(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0004 => {
            match decode_active_dataset_timestamp(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        0x0005 => {
            match decode_pending_dataset_timestamp(tlv_value) {
                Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "null".to_string()),
                Err(e) => format!("{{\"error\": \"{}\"}}", e),
            }
        }
        _ => format!("{{\"error\": \"Unknown attribute ID: {}\"}}", attribute_id),
    }
}

/// Get list of all attributes supported by this cluster
///
/// # Returns
/// Vector of tuples containing (attribute_id, attribute_name)
pub fn get_attribute_list() -> Vec<(u32, &'static str)> {
    vec![
        (0x0000, "BorderRouterName"),
        (0x0001, "BorderAgentID"),
        (0x0002, "ThreadVersion"),
        (0x0003, "InterfaceEnabled"),
        (0x0004, "ActiveDatasetTimestamp"),
        (0x0005, "PendingDatasetTimestamp"),
    ]
}

// Command listing

pub fn get_command_list() -> Vec<(u32, &'static str)> {
    vec![
        (0x00, "GetActiveDatasetRequest"),
        (0x01, "GetPendingDatasetRequest"),
        (0x03, "SetActiveDatasetRequest"),
        (0x04, "SetPendingDatasetRequest"),
    ]
}

pub fn get_command_name(cmd_id: u32) -> Option<&'static str> {
    match cmd_id {
        0x00 => Some("GetActiveDatasetRequest"),
        0x01 => Some("GetPendingDatasetRequest"),
        0x03 => Some("SetActiveDatasetRequest"),
        0x04 => Some("SetPendingDatasetRequest"),
        _ => None,
    }
}

pub fn get_command_schema(cmd_id: u32) -> Option<Vec<crate::clusters::codec::CommandField>> {
    match cmd_id {
        0x00 => Some(vec![]),
        0x01 => Some(vec![]),
        0x03 => Some(vec![
            crate::clusters::codec::CommandField { tag: 0, name: "active_dataset", kind: crate::clusters::codec::FieldKind::OctetString, optional: false, nullable: false },
            crate::clusters::codec::CommandField { tag: 1, name: "breadcrumb", kind: crate::clusters::codec::FieldKind::U64, optional: true, nullable: false },
        ]),
        0x04 => Some(vec![
            crate::clusters::codec::CommandField { tag: 0, name: "pending_dataset", kind: crate::clusters::codec::FieldKind::OctetString, optional: false, nullable: false },
        ]),
        _ => None,
    }
}

pub fn encode_command_json(cmd_id: u32, args: &serde_json::Value) -> anyhow::Result<Vec<u8>> {
    match cmd_id {
        0x00 => Ok(vec![]),
        0x01 => Ok(vec![]),
        0x03 => {
        let active_dataset = crate::clusters::codec::json_util::get_octstr(args, "active_dataset")?;
        let breadcrumb = crate::clusters::codec::json_util::get_opt_u64(args, "breadcrumb")?;
        encode_set_active_dataset_request(active_dataset, breadcrumb)
        }
        0x04 => {
        let pending_dataset = crate::clusters::codec::json_util::get_octstr(args, "pending_dataset")?;
        encode_set_pending_dataset_request(pending_dataset)
        }
        _ => Err(anyhow::anyhow!("unknown command ID: 0x{:02X}", cmd_id)),
    }
}

#[derive(Debug, serde::Serialize)]
pub struct DatasetResponse {
    #[serde(serialize_with = "serialize_opt_bytes_as_hex")]
    pub dataset: Option<Vec<u8>>,
}

// Command response decoders

/// Decode DatasetResponse command response (02)
pub fn decode_dataset_response(inp: &tlv::TlvItemValue) -> anyhow::Result<DatasetResponse> {
    if let tlv::TlvItemValue::List(_fields) = inp {
        let item = tlv::TlvItem { tag: 0, value: inp.clone() };
        Ok(DatasetResponse {
                dataset: item.get_octet_string_owned(&[0]),
        })
    } else {
        Err(anyhow::anyhow!("Expected struct fields"))
    }
}

// Typed facade (invokes + reads)

/// Invoke `GetActiveDatasetRequest` command on cluster `Thread Border Router Management`.
pub async fn get_active_dataset_request(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<DatasetResponse> {
    let tlv = conn.invoke_request2(endpoint, crate::clusters::defs::CLUSTER_ID_THREAD_BORDER_ROUTER_MANAGEMENT, crate::clusters::defs::CLUSTER_THREAD_BORDER_ROUTER_MANAGEMENT_CMD_ID_GETACTIVEDATASETREQUEST, &[]).await?;
    decode_dataset_response(&tlv)
}

/// Invoke `GetPendingDatasetRequest` command on cluster `Thread Border Router Management`.
pub async fn get_pending_dataset_request(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<DatasetResponse> {
    let tlv = conn.invoke_request2(endpoint, crate::clusters::defs::CLUSTER_ID_THREAD_BORDER_ROUTER_MANAGEMENT, crate::clusters::defs::CLUSTER_THREAD_BORDER_ROUTER_MANAGEMENT_CMD_ID_GETPENDINGDATASETREQUEST, &[]).await?;
    decode_dataset_response(&tlv)
}

/// Invoke `SetActiveDatasetRequest` command on cluster `Thread Border Router Management`.
pub async fn set_active_dataset_request(conn: &crate::controller::Connection, endpoint: u16, active_dataset: Vec<u8>, breadcrumb: Option<u64>) -> anyhow::Result<()> {
    conn.invoke_request(endpoint, crate::clusters::defs::CLUSTER_ID_THREAD_BORDER_ROUTER_MANAGEMENT, crate::clusters::defs::CLUSTER_THREAD_BORDER_ROUTER_MANAGEMENT_CMD_ID_SETACTIVEDATASETREQUEST, &encode_set_active_dataset_request(active_dataset, breadcrumb)?).await?;
    Ok(())
}

/// Invoke `SetPendingDatasetRequest` command on cluster `Thread Border Router Management`.
pub async fn set_pending_dataset_request(conn: &crate::controller::Connection, endpoint: u16, pending_dataset: Vec<u8>) -> anyhow::Result<()> {
    conn.invoke_request(endpoint, crate::clusters::defs::CLUSTER_ID_THREAD_BORDER_ROUTER_MANAGEMENT, crate::clusters::defs::CLUSTER_THREAD_BORDER_ROUTER_MANAGEMENT_CMD_ID_SETPENDINGDATASETREQUEST, &encode_set_pending_dataset_request(pending_dataset)?).await?;
    Ok(())
}

/// Read `BorderRouterName` attribute from cluster `Thread Border Router Management`.
pub async fn read_border_router_name(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<String> {
    let tlv = conn.read_request2(endpoint, crate::clusters::defs::CLUSTER_ID_THREAD_BORDER_ROUTER_MANAGEMENT, crate::clusters::defs::CLUSTER_THREAD_BORDER_ROUTER_MANAGEMENT_ATTR_ID_BORDERROUTERNAME).await?;
    decode_border_router_name(&tlv)
}

/// Read `BorderAgentID` attribute from cluster `Thread Border Router Management`.
pub async fn read_border_agent_id(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<Vec<u8>> {
    let tlv = conn.read_request2(endpoint, crate::clusters::defs::CLUSTER_ID_THREAD_BORDER_ROUTER_MANAGEMENT, crate::clusters::defs::CLUSTER_THREAD_BORDER_ROUTER_MANAGEMENT_ATTR_ID_BORDERAGENTID).await?;
    decode_border_agent_id(&tlv)
}

/// Read `ThreadVersion` attribute from cluster `Thread Border Router Management`.
pub async fn read_thread_version(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<u16> {
    let tlv = conn.read_request2(endpoint, crate::clusters::defs::CLUSTER_ID_THREAD_BORDER_ROUTER_MANAGEMENT, crate::clusters::defs::CLUSTER_THREAD_BORDER_ROUTER_MANAGEMENT_ATTR_ID_THREADVERSION).await?;
    decode_thread_version(&tlv)
}

/// Read `InterfaceEnabled` attribute from cluster `Thread Border Router Management`.
pub async fn read_interface_enabled(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<bool> {
    let tlv = conn.read_request2(endpoint, crate::clusters::defs::CLUSTER_ID_THREAD_BORDER_ROUTER_MANAGEMENT, crate::clusters::defs::CLUSTER_THREAD_BORDER_ROUTER_MANAGEMENT_ATTR_ID_INTERFACEENABLED).await?;
    decode_interface_enabled(&tlv)
}

/// Read `ActiveDatasetTimestamp` attribute from cluster `Thread Border Router Management`.
pub async fn read_active_dataset_timestamp(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<Option<u64>> {
    let tlv = conn.read_request2(endpoint, crate::clusters::defs::CLUSTER_ID_THREAD_BORDER_ROUTER_MANAGEMENT, crate::clusters::defs::CLUSTER_THREAD_BORDER_ROUTER_MANAGEMENT_ATTR_ID_ACTIVEDATASETTIMESTAMP).await?;
    decode_active_dataset_timestamp(&tlv)
}

/// Read `PendingDatasetTimestamp` attribute from cluster `Thread Border Router Management`.
pub async fn read_pending_dataset_timestamp(conn: &crate::controller::Connection, endpoint: u16) -> anyhow::Result<Option<u64>> {
    let tlv = conn.read_request2(endpoint, crate::clusters::defs::CLUSTER_ID_THREAD_BORDER_ROUTER_MANAGEMENT, crate::clusters::defs::CLUSTER_THREAD_BORDER_ROUTER_MANAGEMENT_ATTR_ID_PENDINGDATASETTIMESTAMP).await?;
    decode_pending_dataset_timestamp(&tlv)
}

